### ISSUE TITLE
shape error during deep supervision

### ISSUE THREAD

**Issue by aoi-hill** [pytorch/captum#1230]
Hi... my model (inheriting from nn.Module) has a forward method implemented that returns multiple (>1) tensors, each of which is used to calculate one loss. On using it with IG, I am getting following error trace. The model works fine without IG integration, so I wanted to understand where is the problem within IG code.

Traceback (most recent call last):
  File "/home/hrishikesh/Projects/lab/SCNet/Tmp/testing.py", line 65, in <module>
    attributions, approximation_error = ig.attribute(sample_input, target=0,return_convergence_delta=True)
  File "/home/hrishikesh/tools/anaconda3/envs/scnet/lib/python3.10/site-packages/captum/log/__init__.py", line 42, in wrapper
    return func(*args, **kwargs)
  File "/home/hrishikesh/tools/anaconda3/envs/scnet/lib/python3.10/site-packages/captum/attr/_core/integrated_gradients.py", line 286, in attribute
    attributions = self._attribute(
  File "/home/hrishikesh/tools/anaconda3/envs/scnet/lib/python3.10/site-packages/captum/attr/_core/integrated_gradients.py", line 351, in _attribute
    grads = self.gradient_func(
  File "/home/hrishikesh/tools/anaconda3/envs/scnet/lib/python3.10/site-packages/captum/_utils/gradient.py", line 112, in compute_gradients
    outputs = _run_forward(forward_fn, inputs, target_ind, additional_forward_args)
  File "/home/hrishikesh/tools/anaconda3/envs/scnet/lib/python3.10/site-packages/captum/_utils/common.py", line 536, in _run_forward
    return _select_targets(output, target)
  File "/home/hrishikesh/tools/anaconda3/envs/scnet/lib/python3.10/site-packages/captum/_utils/common.py", line 580, in _select_targets
    num_examples = output.shape[0]
AttributeError: 'tuple' object has no attribute 'shape'

**Comment by craymichael** [comment]
Hi, this is covered by the FAQ target section. Captum expects the forward function used for attribution to return a tensor from which one scalar objective per example can be selected; for tuple outputs from deep supervision, wrap the model to select or aggregate the head/loss you want to explain. Closing as documented. https://captum.ai/docs/faq
