### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by dbl001** [pytorch/captum#126]
I am running 'captum' on OS X 10.11.6 (also Ubuntu 16.04LTS).
The example 'python -m captum.insights.example' gets and Internal Server Error when I try
to connect to http://localhost:51283/ with Safari.

Any ideas?

```$ pytest -ra
============================= test session starts ==============================
platform darwin -- Python 3.6.7, pytest-5.0.1, py-1.8.0, pluggy-0.13.0
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/Users/davidlaxer/captum/.hypothesis/examples')
rootdir: /Users/davidlaxer/captum
plugins: hypothesis-3.88.3
collected 212 items                                                            

tests/attr/test_approximation_methods.py ....                            [  1%]
tests/attr/test_common.py ........                                       [  5%]
tests/attr/test_data_parallel.py ssssssssssssssss                        [ 13%]
tests/attr/test_deeplift_basic.py ......                                 [ 16%]
tests/attr/test_deeplift_classification.py .....F..                      [ 19%]
tests/attr/test_gradient.py ........                                     [ 23%]
tests/attr/test_gradient_shap.py ...                                     [ 25%]
tests/attr/test_input_x_gradient.py .........                            [ 29%]
tests/attr/test_integrated_gradients_basic.py ........................   [ 40%]
tests/attr/test_integrated_gradients_classification.py ........          [ 44%]
tests/attr/test_internal_influence.py ..........                         [ 49%]
tests/attr/test_layer_activation.py ......                               [ 51%]
tests/attr/test_layer_conductance.py .............                       [ 58%]
tests/attr/test_layer_gradient_x_activation.py ......                    [ 60%]
tests/attr/test_neuron_conductance.py .........                          [ 65%]
tests/attr/test_neuron_gradient.py ........                              [ 68%]
tests/attr/test_neuron_integrated_gradients.py ........                  [ 72%]
tests/attr/test_saliency.py .........                                    [ 76%]
tests/attr/test_targets.py ...................................           [ 93%]
tests/attr/test_utils_batching.py .........                              [ 97%]
tests/attr/models/test_base.py .                                         [ 98%]
tests/attr/models/test_pytext.py ss                                      [ 99%]
tests/insights/test_contribution.py ..                                   [100%]

=================================== FAILURES ===================================
_____________ Test.test_softmax_classification_batch_zero_baseline _____________

self = <tests.attr.test_deeplift_classification.Test testMethod=test_softmax_classification_batch_zero_baseline>

    def test_softmax_classification_batch_zero_baseline(self):
        num_in = 40
        input = torch.arange(0.0, num_in * 3.0, requires_grad=True).reshape(3, num_in)
        baselines = 0 * input
    
        model = SoftmaxDeepLiftModel(num_in, 20, 10)
        dl = DeepLift(model)
    
>       self.softmax_classification(model, dl, input, baselines)

tests/attr/test_deeplift_classification.py:54: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/attr/test_deeplift_classification.py:117: in softmax_classification
    self._assert_attributions(model, attributions, input, baselines, delta, target2)
tests/attr/test_deeplift_classification.py:129: in _assert_attributions
    "some samples".format(delta),
E   AssertionError: False is not true : The sum of attribution values tensor([0.0008, 0.0023, 0.0039]) is not nearly equal to the difference between the endpoint for some samples
=============================== warnings summary ===============================
/Users/davidlaxer/anaconda/envs/ai/lib/python3.6/site-packages/IPython/lib/pretty.py:91
  /Users/davidlaxer/anaconda/envs/ai/lib/python3.6/site-packages/IPython/lib/pretty.py:91: DeprecationWarning: IPython.utils.signatures backport for Python 2 is deprecated in IPython 6, which only supports Python 3
    from IPython.utils.signatures import signature

/Users/davidlaxer/anaconda/envs/ai/lib/python3.6/site-packages/IPython/utils/module_paths.py:28
  /Users/davidlaxer/anaconda/envs/ai/lib/python3.6/site-packages/IPython/utils/module_paths.py:28: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp

tests/attr/test_deeplift_basic.py::Test::test_relu_deeplift
tests/attr/test_deeplift_basic.py::Test::test_relu_deeplift_batch
tests/attr/test_deeplift_basic.py::Test::test_relu_deeplift_batch_4D_input
tests/attr/test_deeplift_basic.py::Test::test_relu_deeplift_multi_ref
tests/attr/test_deeplift_basic.py::Test::test_relu_linear_deeplift
tests/attr/test_deeplift_basic.py::Test::test_tanh_deeplift
tests/attr/test_deeplift_classification.py::Test::test_convnet_with_maxpool1d
tests/attr/test_deeplift_classification.py::Test::test_convnet_with_maxpool2d
tests/attr/test_deeplift_classification.py::Test::test_convnet_with_maxpool3d
tests/attr/test_deeplift_classification.py::Test::test_sigmoid_classification
tests/attr/test_deeplift_classification.py::Test::test_softmax_classification_batch_multi_baseline
tests/attr/test_deeplift_classification.py::Test::test_softmax_classification_batch_zero_baseline
tests/attr/test_deeplift_classification.py::Test::test_softmax_classification_multi_baseline
tests/attr/test_deeplift_classification.py::Test::test_softmax_classification_zero_baseline
tests/attr/test_targets.py::Test::test_multi_target_deep_lift
tests/attr/test_targets.py::Test::test_multi_target_deep_lift_shap
tests/attr/test_targets.py::Test::test_simple_target_deep_lift
tests/attr/test_targets.py::Test::test_simple_target_deep_lift_shap
tests/attr/test_targets.py::Test::test_simple_target_deep_lift_shap_single_tensor
tests/attr/test_targets.py::Test::test_simple_target_deep_lift_shap_tensor
  /Users/davidlaxer/captum/captum/attr/_core/deep_lift.py:327: UserWarning: Setting forward, backward hooks and attributes on non-linear
                 activations. The hooks and attributes will be removed
              after the attribution is finished
    after the attribution is finished"""

tests/attr/test_gradient.py::Test::test_apply_gradient_reqs
tests/attr/test_layer_conductance.py::Test::test_matching_conv_with_baseline_conductance
tests/attr/test_layer_conductance.py::Test::test_matching_pool1_conductance
tests/attr/test_layer_conductance.py::Test::test_matching_pool2_conductance
tests/attr/test_neuron_gradient.py::Test::test_matching_intermediate_gradient
tests/attr/test_neuron_gradient.py::Test::test_simple_gradient_input_linear1
tests/attr/test_neuron_gradient.py::Test::test_simple_gradient_input_relu2
tests/attr/test_neuron_gradient.py::Test::test_simple_gradient_multi_input_linear1
tests/attr/test_neuron_gradient.py::Test::test_simple_gradient_multi_input_linear2
tests/attr/test_targets.py::Test::test_multi_target_deep_lift
tests/attr/test_targets.py::Test::test_multi_target_input_x_gradient
tests/attr/test_targets.py::Test::test_multi_target_saliency
tests/attr/test_targets.py::Test::test_simple_target_deep_lift
tests/attr/test_targets.py::Test::test_simple_target_input_x_gradient
tests/attr/test_targets.py::Test::test_simple_target_saliency
tests/attr/test_targets.py::Test::test_simple_target_saliency_tensor
  /Users/davidlaxer/captum/captum/attr/_utils/gradient.py:27: UserWarning: Input Tensor 0 did not already require gradients, required_grads has been set automatically.
    "required_grads has been set automatically." % index

tests/attr/test_gradient.py::Test::test_apply_gradient_reqs
  /Users/davidlaxer/captum/captum/attr/_utils/gradient.py:34: UserWarning: Input Tensor 1 had a non-zero gradient tensor, which is being reset to 0.
    "which is being reset to 0." % index

tests/attr/test_gradient.py::Test::test_apply_gradient_reqs
tests/attr/test_neuron_gradient.py::Test::test_simple_gradient_multi_input_linear2
  /Users/davidlaxer/captum/captum/attr/_utils/gradient.py:27: UserWarning: Input Tensor 2 did not already require gradients, required_grads has been set automatically.
    "required_grads has been set automatically." % index

tests/attr/test_neuron_gradient.py::Test::test_simple_gradient_multi_input_linear1
tests/attr/test_neuron_gradient.py::Test::test_simple_gradient_multi_input_linear2
  /Users/davidlaxer/captum/captum/attr/_utils/gradient.py:27: UserWarning: Input Tensor 1 did not already require gradients, required_grads has been set automatically.
    "required_grads has been set automatically." % index

tests/attr/models/test_base.py::Test::test_interpretable_embedding_base
  /Users/davidlaxer/captum/captum/attr/_models/base.py:168: UserWarning: In order to make embedding layers more interpretable they will
          be replaced with an interpretable embedding layer which wraps the
          original embedding layer and takes word embedding vectors as inputs of
          the forward function. This allows to generate baselines for word
          embeddings and compute attributions for each embedding dimension.
          The original embedding layer must be set
          back by calling `remove_interpretable_embedding_layer` function
          after model interpretation is finished.
    after model interpretation is finished."""

tests/insights/test_contribution.py::Test::test_multi_features
tests/insights/test_contribution.py::Test::test_multi_features
tests/insights/test_contribution.py::Test::test_multi_features
tests/insights/test_contribution.py::Test::test_multi_features
tests/insights/test_contribution.py::Test::test_one_feature
tests/insights/test_contribution.py::Test::test_one_feature
tests/insights/test_contribution.py::Test::test_one_feature
tests/insights/test_contribution.py::Test::test_one_feature
  /Users/davidlaxer/anaconda/envs/ai/lib/python3.6/site-packages/matplotlib/colors.py:101: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
    ret = np.asscalar(ex)

tests/insights/test_contribution.py::Test::test_multi_features
tests/insights/test_contribution.py::Test::test_multi_features
tests/insights/test_contribution.py::Test::test_one_feature
tests/insights/test_contribution.py::Test::test_one_feature
  /Users/davidlaxer/anaconda/envs/ai/lib/python3.6/site-packages/matplotlib/image.py:424: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
    a_min = np.asscalar(a_min.astype(scaled_dtype))

tests/insights/test_contribution.py::Test::test_multi_features
tests/insights/test_contribution.py::Test::test_multi_features
tests/insights/test_contribution.py::Test::test_one_feature
tests/insights/test_contribution.py::Test::test_one_feature
  /Users/davidlaxer/anaconda/envs/ai/lib/python3.6/site-packages/matplotlib/image.py:425: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
    a_max = np.asscalar(a_max.astype(scaled_dtype))

-- Docs: https://docs.pytest.org/en/latest/warnings.html
=========================== short test summary info ============================
SKIPPED [1] tests/attr/test_data_parallel.py:116: Skipping GPU test since CUDA not available.
SKIPPED [1] tests/attr/test_data_parallel.py:187: Skipping GPU test since CUDA not available.
SKIPPED [1] tests/attr/test_data_parallel.py:254: Skipping GPU test since CUDA not available.
SKIPPED [1] tests/attr/test_data_parallel.py:38: Skipping GPU test since CUDA not available.
SKIPPED [1] tests/attr/test_data_parallel.py:68: Skipping GPU test since CUDA not available.
SKIPPED [1] tests/attr/test_data_parallel.py:98: Skipping GPU test since CUDA not available.
SKIPPED [1] tests/attr/test_data_parallel.py:137: Skipping GPU test since CUDA not available.
SKIPPED [1] tests/attr/test_data_parallel.py:168: Skipping GPU test since CUDA not available.
SKIPPED [1] tests/attr/test_data_parallel.py:219: Skipping GPU test since CUDA not available.
SKIPPED [1] tests/attr/test_data_parallel.py:24: Skipping GPU test since CUDA not available.
SKIPPED [1] tests/attr/test_data_parallel.py:56: Skipping GPU test since CUDA not available.
SKIPPED [1] tests/attr/test_data_parallel.py:84: Skipping GPU test since CUDA not available.
SKIPPED [1] tests/attr/test_data_parallel.py:123: Skipping GPU test since CUDA not available.
SKIPPED [1] tests/attr/test_data_parallel.py:154: Skipping GPU test since CUDA not available.
SKIPPED [1] tests/attr/test_data_parallel.py:200: Skipping GPU test since CUDA not available.
SKIPPED [1] tests/attr/test_data_parallel.py:235: Skipping GPU test since CUDA not available.
SKIPPED [1] tests/attr/models/test_pytext.py:81: Skip the test since PyText is not installed
SKIPPED [1] tests/attr/models/test_pytext.py:68: Skip the test since PyText is not installed
FAILED tests/attr/test_deeplift_classification.py::Test::test_softmax_classification_batch_zero_baseline
======= 1 failed, 193 passed, 18 skipped, 60 warnings in 1188.87 seconds =======

$ python -m captum.insights.example

Fetch data and view Captum Insights at http://localhost:51283/

<IPython.lib.display.IFrame object at 0x1211f1c18>
```

![Screen Shot 2019-10-18 at 9 08 09 AM](https://user-images.githubusercontent.com/3105499/67110223-11061100-f187-11e9-8c70-84e688395e7c.png)

**Comment by edward-io** [comment]
Hi, apologies for the unhelpful error message. Can you try running the script (located here: https://github.com/pytorch/captum/blob/master/captum/insights/example.py) but replace the last line from `visualizer.render()` to `visualizer.render(debug=True)`

**Comment by dbl001** [comment]
(ai) MacBook-Pro:captum davidlaxer$ python -m captum.insights.example

Fetch data and view Captum Insights at http://localhost:50913/

<IPython.lib.display.IFrame object at 0x1181d9c18>
^CException ignored in: <module 'threading' from '/Users/davidlaxer/anaconda/envs/ai/lib/python3.6/threading.py'>
Traceback (most recent call last):
  File "/Users/davidlaxer/anaconda/envs/ai/lib/python3.6/threading.py", line 1294, in _shutdown
    t.join()
  File "/Users/davidlaxer/anaconda/envs/ai/lib/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/Users/davidlaxer/anaconda/envs/ai/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
(ai) MacBook-Pro:captum davidlaxer$ python -m captum.insights.example

Fetch data and view Captum Insights at http://localhost:51283/

<IPython.lib.display.IFrame object at 0x1211f1c18>
^CException ignored in: <module 'threading' from '/Users/davidlaxer/anaconda/envs/ai/lib/python3.6/threading.py'>
Traceback (most recent call last):
  File "/Users/davidlaxer/anaconda/envs/ai/lib/python3.6/threading.py", line 1294, in _shutdown
    t.join()
  File "/Users/davidlaxer/anaconda/envs/ai/lib/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/Users/davidlaxer/anaconda/envs/ai/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
(ai) MacBook-Pro:captum davidlaxer$ find . -name example.py -ls
1684510115        8 -rw-r--r--    1 davidlaxer       staff                2499 Oct 17 12:31 ./captum/insights/example.py
(ai) MacBook-Pro:captum davidlaxer$ vi ./captum/insights/example.py
(ai) MacBook-Pro:captum davidlaxer$ python -m captum.insights.example

Fetch data and view Captum Insights at http://localhost:53687/

 * Running on http://127.0.0.1:53687/ (Press CTRL+C to quit)
<IPython.lib.display.IFrame object at 0x11ad02ac8>
[2019-10-18 19:08:12,450] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/Users/davidlaxer/anaconda/envs/ai/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/davidlaxer/anaconda/envs/ai/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/davidlaxer/anaconda/envs/ai/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/davidlaxer/anaconda/envs/ai/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/davidlaxer/anaconda/envs/ai/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/davidlaxer/anaconda/envs/ai/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/davidlaxer/captum/captum/insights/server.py", line 60, in index
    return render_template("index.html")
  File "/Users/davidlaxer/anaconda/envs/ai/lib/python3.6/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/davidlaxer/anaconda/envs/ai/lib/python3.6/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/davidlaxer/anaconda/envs/ai/lib/python3.6/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/davidlaxer/anaconda/envs/ai/lib/python3.6/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/davidlaxer/anaconda/envs/ai/lib/python3.6/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/davidlaxer/anaconda/envs/ai/lib/python3.6/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/davidlaxer/anaconda/envs/ai/lib/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
127.0.0.1 - - [18/Oct/2019 19:08:12] "GET / HTTP/1.1" 500 -
127.0.0.1 - - [18/Oct/2019 19:08:13] "GET /apple-touch-icon-precomposed.png HTTP/1.1" 404 -
127.0.0.1 - - [18/Oct/2019 19:08:13] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [18/Oct/2019 19:08:13] "GET /apple-touch-icon.png HTTP/1.1" 404 -

**Comment by dbl001** [comment]
I am running from source.

**Comment by dbl001** [comment]
This message indicates the exception is a flask template issue:

jinja2.exceptions.TemplateNotFound: index.html

**Comment by edward-io** [comment]
@dbl001:

Did the instructions on building Captum Insights work for you? Not having an `index.html` file seems to indicate that the Javascript build wasn't successful.

From the README:

```
conda install -c conda-forge yarn
BUILD_INSIGHTS=1 python setup.py develop
python captum/insights/example.py
```

**Comment by dbl001** [comment]
Capture insights works on OS X, but for some reason I can not connect to the service from my Mac when I run Captum on Ubuntu 16.014LTS.
Netstat shows that there is a listening connection on the port, but I Safari say connection refused.

$ python -m captum.insights.example

Fetch data and view Captum Insights at http://localhost:33948/

 * Running on http://127.0.0.1:33948/ (Press CTRL+C to quit)
<IPython.lib.display.IFrame object at 0x7f13bd1aaf98>


$ netstat -a | grep 33948
tcp        0      0 localhost:33948         *:*                     LISTEN  

The port (e.g. 33948 ) is open in my AWS security group.

**Comment by orionr** [comment]
Hi @dbl001, any update on this? Thanks.

**Comment by LeeKyungwook** [comment]
Hi @dbl001 , any update on this? Thx!

**Comment by edward-io** [comment]
Closing this issue out since it's fairly old, and Insights have had a couple of updates since then. Please open a new issue if this still occurs. Thanks!
