### ISSUE TITLE
visualizer.render not working in jupyter notebook (javascript error)

### ISSUE THREAD

**Issue by ghazizadehlab** [pytorch/captum#1313]
I am running pytorch on mac and can run captum.insights but not the visual renderer

## 🐛 Bug
visualizer.render(debug=True)
[Open Browser Console for more detailed log - Double click to close this message]
Failed to load model class 'CaptumInsightsModel' from module 'jupyter-captum-insights'
Error: No version of module jupyter-captum-insights is registered
    at f.loadClass (http://localhost:8813/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/446.fdf8b1b233cb8c1783f6.js?v=fdf8b1b233cb8c1783f6:1:74920)
    at f.loadModelClass (http://localhost:8813/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/327.68dbf8491690b3aff1e7.js?v=68dbf8491690b3aff1e7:1:10729)
    at f._make_model (http://localhost:8813/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/327.68dbf8491690b3aff1e7.js?v=68dbf8491690b3aff1e7:1:7517)
    at f.new_model (http://localhost:8813/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/327.68dbf8491690b3aff1e7.js?v=68dbf8491690b3aff1e7:1:5137)
    at f.handle_comm_open (http://localhost:8813/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/327.68dbf8491690b3aff1e7.js?v=68dbf8491690b3aff1e7:1:3894)
    at _handleCommOpen (http://localhost:8813/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/446.fdf8b1b233cb8c1783f6.js?v=fdf8b1b233cb8c1783f6:1:73457)
    at f._handleCommOpen (http://localhost:8813/static/notebook/3676.bundle.js:1:30954)
    at async f._handleMessage (http://localhost:8813/static/notebook/3676.bundle.js:1:32848)

captum.__version__
'0.7.0'

Selected Jupyter core packages...
IPython          : 8.26.0
ipykernel        : 6.29.5
ipywidgets       : 8.1.3
jupyter_client   : 8.6.2
jupyter_core     : 5.7.2
jupyter_server   : 2.14.2
jupyterlab       : 4.2.3
nbclient         : 0.10.0
nbconvert        : 7.16.4
nbformat         : 5.10.4
notebook         : 7.2.1
qtconsole        : 5.5.2
traitlets        : 5.14.3

**Comment by wbuchanan** [comment]
I ran into the same issue.  I've tried installing things in a new environment and even when `jupyter nbextension install --py --symlink --sys-prefix captum.insights.attr_vis.widget` indicates that it was installed, the same exception is thrown (even after running ` jupyter nbextension enable captum.insights.attr_vis.widget --py --sys-prefix` after the seemingly successful install).  What's worse is that several of the alternative visualization methods referenced in the tutorials are undocumented.

**Comment by nsh2207** [comment]
I am also facing the same issue, I tried @wbuchanan did with no success

**Comment by nsh2207** [comment]
could you find any solution? @wbuchanan @ghazizadehlab ?

**Comment by wbuchanan** [comment]
I didn’t have sufficient time left on my project to try figuring out what the issue is so we gave up on creating visualizations based on actual examples from the clients data.Sent from my iPhoneOn Oct 12, 2024, at 13:01, nsh2207 ***@***.***> wrote:﻿
could you find any solution? @wbuchanan @ghazizadehlab ?

**Comment by craymichael** [comment]
Unfortunately, we no longer support Captum Insights as of the newest release, version 0.9.0. This is now community supported by going to an older version, but we will no longer support this. Apologies for the inconvenience.
