### ISSUE TITLE
'EpsilonRule' object has no attribute 'relevance_output'

### ISSUE THREAD

**Issue by Evansika959** [pytorch/captum#1363]
I'm encountering an AttributeError while using LayerLRP with the SwitchTransformersAttention module in my custom transformer model. The error occurs when I attempt to compute the attributions using LayerLRP and seems to be related to the assigned LRP rule.

Here is the full error traceback:
Traceback (most recent call last):
  File "/home/xinting/clones/Switch_Magic/get_de_en_LRP.py", line 83, in <module>
    attributions = layer_lrp.attribute(
  File "/opt/conda/lib/python3.10/site-packages/captum/attr/_core/layer/layer_lrp.py", line 233, in attribute
    relevances = self._get_output_relevance(output)
  File "/opt/conda/lib/python3.10/site-packages/captum/attr/_core/layer/layer_lrp.py", line 282, in _get_output_relevance
    return self._get_single_output_relevance(self.layer, output)
  File "/opt/conda/lib/python3.10/site-packages/captum/attr/_core/layer/layer_lrp.py", line 258, in _get_single_output_relevance
    normalized_relevances = layer.rule.relevance_output
AttributeError: 'EpsilonRule' object has no attribute 'relevance_output'

The error suggests that EpsilonRule lacks an attribute relevance_output, which Captum's LayerLRP seems to be attempting to access. The error occurs when attempting to use LayerLRP for relevance propagation through the SwitchTransformersAttention layer of my custom transformer model, specifically when the assigned rule does not seem to meet the expected requirements.

Below is my code snippet:
`from captum.attr import LayerLRP
from captum.attr._utils.lrp_rules import EpsilonRule
import torch

# Load the model and tokenizer
model_name = 'google/switch-base-8'
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = SwitchTransformersForConditionalGeneration.from_pretrained(model_name)

# Assign LRP rules
for name, module in model.named_modules():
    if isinstance(module, SwitchTransformersAttention):
        setattr(module, 'rule', EpsilonRule())

# Define the target layer and initialize LayerLRP
target_layer = model.decoder.block[0].layer[0].SelfAttention
layer_lrp = LayerLRP(model, layer=target_layer)

# Compute attributions
attributions = layer_lrp.attribute(
    inputs=input_embeds,
    additional_forward_args=(attention_mask, decoder_inputs_embeds),
    attribute_to_layer_input=False,
    verbose=True
)`

**Comment by chillerb** [comment]
Hi @Evansika959,
You are right, when EpsilonRule is initialized, it actually does not have `relevance_input` or `relevance_output` attributes.
However, it is a bit odd
Default LRP attribution therefore initializes those attributes before accessing them:

```python
# lrp.py
def _check_and_attach_rules(self) -> None:
        for layer in self.layers:
            if hasattr(layer, "rule"):
                layer.activations = {}  # type: ignore
                layer.rule.relevance_input = defaultdict(list)  # type: ignore
                layer.rule.relevance_output = {}  # type: ignore
```

However, that `_check_and_attach_rules` function *should* be called by LayerLRP on `attribute`, so it is a little bit weird, why your layers don't seem to be properly initialized?

```python
# layer_lrp.py
def attribute(...):
        self.verbose = verbose
        self._original_state_dict = self.model.state_dict()
        self.layers = []
        self._get_layers(self.model)
        self._check_and_attach_rules()
```

As a workaround, just initialize the SelfAttention layers and rules with:
```python
layer.activations = {}  # type: ignore
layer.rule.relevance_input = defaultdict(list)  # type: ignore
layer.rule.relevance_output = {}  # type: ignore
```

**Comment by cyrjano** [comment]
It seems that the workaround work. I am closing this issue.
