### ISSUE TITLE
Captum Insights build fails on Linux  Ubuntu18.04

### ISSUE THREAD

**Issue by elboyran** [pytorch/captum#294]
Cannot build and launch Captum insights on Linux Ubutnu18.04 (inside VM VirtualBox):

> 
> (captum) elena@elena-VirtualBox:~/eStep/XAI/Software/captum$ conda install -c conda-forge yarn
> Collecting package metadata (repodata.json): done
> Solving environment: done
> 
> # All requested packages already installed.
> (captum) elena@elena-VirtualBox:~/eStep/XAI/Software/captum$ BUILD_INSIGHTS=1 python setup.py develop
> -- Building version 0.2.0
> -- Building Captum Insights
> Running: ./scripts/build_insights.sh
> ~/eStep/XAI/Software/captum/captum/insights/frontend ~/eStep/XAI/Software/captum
> -----------------------------------
> Install Dependencies
> -----------------------------------
> yarn install v1.22.0
> [1/4] Resolving packages...
> [2/4] Fetching packages...
> info fsevents@2.0.7: The platform "linux" is incompatible with this module.
> info "fsevents@2.0.7" is an optional dependency and failed compatibility check. Excluding it from installation.
> info fsevents@1.2.11: The platform "linux" is incompatible with this module.
> info "fsevents@1.2.11" is an optional dependency and failed compatibility check. Excluding it from installation.
> [3/4] Linking dependencies...
> warning " > @babel/plugin-proposal-class-properties@7.7.4" has unmet peer dependency "@babel/core@^7.0.0-0".
> warning "@babel/plugin-proposal-class-properties > @babel/helper-create-class-features-plugin@7.7.4" has unmet peer dependency "@babel/core@^7.0.0".
> warning " > babel-loader@8.0.6" has unmet peer dependency "@babel/core@^7.0.0".
> warning " > babel-loader@8.0.6" has unmet peer dependency "webpack@>=2".
> warning "react-scripts > @typescript-eslint/eslint-plugin > tsutils@3.17.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
> warning " > react-tag-autocomplete@5.11.2" has unmet peer dependency "prop-types@^15.0.0".
> warning " > webpack-cli@3.3.10" has unmet peer dependency "webpack@4.x.x".
> error An unexpected error occurred: "EPERM: operation not permitted, symlink '../../../parser/bin/babel-parser.js' -> '/home/elena/eStep/XAI/Software/captum/captum/insights/frontend/node_modules/@babel/core/node_modules/.bin/parser'".
> info If you think this is a bug, please open a bug report with the information provided in "/home/elena/eStep/XAI/Software/captum/captum/insights/frontend/yarn-error.log".
> info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
> Traceback (most recent call last):
>   File "setup.py", line 105, in <module>
>     build_insights()
>   File "setup.py", line 88, in build_insights
>     subprocess.check_call(command)
>   File "/home/elena/anaconda3/envs/captum/lib/python3.7/subprocess.py", line 347, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command './scripts/build_insights.sh' returned non-zero exit status 1.
> (captum) elena@elena-VirtualBox:~/eStep/XAI/Software/captum$ 
>

**Comment by orionr** [comment]
@edward-io or @J0Nreynolds can you take a look here? Seems like some yarn dependencies for the build and install aren't available? @elboyran do you have any restrictions on installing (proxy required, etc) on that VM?

**Comment by elboyran** [comment]
Not that I am aware of.

**Comment by orionr** [comment]
Is your VM running on a Windows machine? Just saw https://stackoverflow.com/questions/42433649/npm-install-error-eperm-operation-not-permitted-symlink-mkdirp-bin-cmd-js  Might also have to do with permission problems on the folder? Seems like the real issue is

```
error An unexpected error occurred: "EPERM: operation not permitted, symlink '../../../parser/bin/babel-parser.js' -> '/home/elena/eStep/XAI/Software/captum/captum/insights/frontend/node_modules/@babel/core/node_modules/.bin/parser'".
```

**Comment by orionr** [comment]
Another related note that might help: https://github.com/angular/angular-cli/issues/641

**Comment by edward-io** [comment]
I don't have a Windows machine to test this on at the moment, but these issues seem relevant: https://github.com/npm/npm/issues/5824  https://github.com/yarnpkg/yarn/issues/3343.

It's possible there's some conflict between filesystems. Can you try the following:

1) Check that you're using a non-NTFS/non-FAT filesystem for your VM. If not, create one or move your files into something like EXT4.
2) Run your VM with Administrator permissions on Windows.

**Comment by NarineK** [comment]
@elboyran is this still an open problem ? Can we close this issue ?

**Comment by edward-io** [comment]
Closing due to inactivity. Please open a new issue if you're still encountering this issue. Thanks!
