### ISSUE TITLE
dimension issue - batch size broadcast to num_steps, mixed with other dim

### ISSUE THREAD

**Issue by jiacheng-xu** [pytorch/captum#466]
Basic description of the issue here:
- the algorithm I use: LayerIntegratedGradients
- I have the num_steps=50. when the model runs the IG approximation with num_steps times, it seems to mess up with the batch size of a key_value matrix in the Transformer model. 
- My interpretation of the error message:     "prev_key = _prev_key.view(bsz * self.num_heads, -1, self.head_dim)" ==>bsz is set to be 1 here, num_heads should be 16; "RuntimeError: shape '[800, -1, 64]' is invalid for input of size 4096" ==> the bsz here is now 50 which is the num_steps * bsz.

Any hints about what to do with this?

> INFO:Loading facebook/bart-large-xsum
run normal
torch.Size([1, 50264])
torch.Size([1, 50264])
torch.Size([50, 50264])
tensor([[[0., -0., -0.,  ..., -0., -0., -0.]]], dtype=torch.float64,
       grad_fn=<MulBackward0>)
run normal
torch.Size([1, 50264])
torch.Size([1, 50264])
Traceback (most recent call last):
  File "/home/jcxu/interpret-sum/run_transformers.py", line 159, in <module>
    main()
  File "/home/jcxu/interpret-sum/run_transformers.py", line 131, in main
    sgen.run_attribution(data_w_label.data['input_ids'], None)
  File "/home/jcxu/interpret-sum/util.py", line 105, in run_attribution
    attribution_result = self.attr.attribute(inputs=input_doc, baselines=reference_indices,
  File "/home/jcxu/miniconda3/lib/python3.8/site-packages/captum/attr/_core/layer/layer_integrated_gradients.py", line 352, in attribute
    attributions = self.ig.attribute(
  File "/home/jcxu/miniconda3/lib/python3.8/site-packages/captum/attr/_core/integrated_gradients.py", line 278, in attribute
    grads = _batched_operator(
  File "/home/jcxu/miniconda3/lib/python3.8/site-packages/captum/attr/_utils/batching.py", line 156, in _batched_operator
    all_outputs = [
  File "/home/jcxu/miniconda3/lib/python3.8/site-packages/captum/attr/_utils/batching.py", line 157, in <listcomp>
    operator(
  File "/home/jcxu/miniconda3/lib/python3.8/site-packages/captum/attr/_core/layer/layer_integrated_gradients.py", line 333, in gradient_func
    output = _run_forward(
  File "/home/jcxu/miniconda3/lib/python3.8/site-packages/captum/attr/_utils/common.py", line 500, in _run_forward
    output = forward_func(
  File "/home/jcxu/interpret-sum/util.py", line 145, in forward_step
    outputs = self.model(**model_inputs, use_cache=True, return_dict=True)
  File "/home/jcxu/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jcxu/miniconda3/lib/python3.8/site-packages/transformers/modeling_bart.py", line 1066, in forward
    outputs = self.model(
  File "/home/jcxu/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jcxu/miniconda3/lib/python3.8/site-packages/transformers/modeling_bart.py", line 930, in forward
    decoder_outputs = self.decoder(
  File "/home/jcxu/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jcxu/miniconda3/lib/python3.8/site-packages/transformers/modeling_bart.py", line 579, in forward
    x, layer_self_attn, layer_past = decoder_layer(
  File "/home/jcxu/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jcxu/miniconda3/lib/python3.8/site-packages/transformers/modeling_bart.py", line 417, in forward
    x, self_attn_weights = self.self_attn(
  File "/home/jcxu/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jcxu/miniconda3/lib/python3.8/site-packages/transformers/modeling_bart.py", line 690, in forward
    k, v, key_padding_mask = self._use_saved_state(k, v, saved_state, key_padding_mask, static_kv, bsz)
  File "/home/jcxu/miniconda3/lib/python3.8/site-packages/transformers/modeling_bart.py", line 744, in _use_saved_state
    prev_key = _prev_key.view(bsz * self.num_heads, -1, self.head_dim)
RuntimeError: shape '[800, -1, 64]' is invalid for input of size 4096
Process finished with exit code 1

**Comment by heytitle** [comment]
@jiacheng-xu I would suggest you checking  https://github.com/pytorch/captum/issues/427.

**Comment by jiacheng-xu** [comment]
hi, @heytitle thanks for your reference.
It's definitely relevant to my issue, but the matrix I had a problem with is not the input embedding. It's one of the additional args. All of the Transformer architectures (as far as I know) don't use seq_first. Do you know where does the framework handle the broadcast?

**Comment by NarineK** [comment]
@jiacheng-xu, do you still observe this issue ?

**Comment by jiacheng-xu** [comment]
@NarineK I did not end up using the framework due to these issues. Probably there are some fixes and updates but I did not keep tracking of it.
