### ISSUE TITLE
NeuronConductance module

### ISSUE THREAD

**Issue by Thzn** [pytorch/captum#623]
Hi,

I'm trying to compute NeuronConductance for an Autoencoder model. Specifically, I need to find the neuron-wise conductance of the latent space returned by the Encoder network. 

My encoder is a simple model and the final output of the model is returned by a Linear layer (torch.nn.Linear). 

```
model = Encoder()
conduct_module = NeuronConductance(model, model.linear2)

# attribution for the zeroth neuron, X is the input to the model 
attribution = conduct_module.attribute(X, (0,))

```
For this, I'm getting the following error message
`
Traceback (most recent call last):
  File "conductance-plot.py", line 191, in <module>
    attribution = conduct_module.attribute(X, (0,))
  File "/home/n10651811/.local/lib/python3.7/site-packages/captum/log/__init__.py", line 35, in wrapper
    return func(*args, **kwargs)
  File "/home/n10651811/.local/lib/python3.7/site-packages/captum/attr/_utils/common.py", line 387, in wrapper
    return func(*args, **kwargs)
  File "/home/n10651811/.local/lib/python3.7/site-packages/captum/attr/_core/neuron/neuron_conductance.py", line 283, in attribute
    attribute_to_neuron_input=attribute_to_neuron_input,
  File "/home/n10651811/.local/lib/python3.7/site-packages/captum/attr/_core/neuron/neuron_conductance.py", line 343, in _attribute
    attribute_to_layer_input=attribute_to_neuron_input,
  File "/home/n10651811/.local/lib/python3.7/site-packages/captum/_utils/gradient.py", line 603, in compute_layer_gradients_and_eval
    "Target not provided when necessary, cannot"
AssertionError: Target not provided when necessary, cannot take gradient with respect to multiple outputs.
`

The code is almost similar to the example provided on the website. Can you please provide me with some suggestions?

Is this error message related to **target** variable in the attribute function? For this, according to the documentation, I passed a tensor of the latent space (z) with values relevant to neuron 0 (`z[:,0]`). For this also, the method returned an error. 

```
z = model(X)
attribution = conduct_module.attribute(X, (0,), target=z[:,0])

```

`Traceback (most recent call last):
  File "conductance-plot.py", line 191, in <module>
    attribution = conduct_module.attribute(X, (0,), target=z[:,0])
  File "/home/n10651811/.local/lib/python3.7/site-packages/captum/log/__init__.py", line 35, in wrapper
    return func(*args, **kwargs)
  File "/home/n10651811/.local/lib/python3.7/site-packages/captum/attr/_utils/common.py", line 387, in wrapper
    return func(*args, **kwargs)
  File "/home/n10651811/.local/lib/python3.7/site-packages/captum/attr/_core/neuron/neuron_conductance.py", line 283, in attribute
    attribute_to_neuron_input=attribute_to_neuron_input,
  File "/home/n10651811/.local/lib/python3.7/site-packages/captum/attr/_core/neuron/neuron_conductance.py", line 343, in _attribute
    attribute_to_layer_input=attribute_to_neuron_input,
  File "/home/n10651811/.local/lib/python3.7/site-packages/captum/_utils/gradient.py", line 600, in compute_layer_gradients_and_eval
    forward_hook_with_return=True,
  File "/home/n10651811/.local/lib/python3.7/site-packages/captum/_utils/gradient.py", line 299, in _forward_layer_distributed_eval
    additional_forward_args=additional_forward_args,
  File "/home/n10651811/.local/lib/python3.7/site-packages/captum/_utils/common.py", line 441, in _run_forward
    return _select_targets(output, target)
  File "/home/n10651811/.local/lib/python3.7/site-packages/captum/_utils/common.py", line 458, in _select_targets
    return torch.gather(output, 1, target.reshape(len(output), 1))
RuntimeError: gather_out_cuda(): Expected dtype int64 for index
`

**Comment by bilalsal** [comment]
Hi @Thzn,

Yes, Captum needs to know for which target you want to compute the attribution.
The target can be specified by index not by value (see details in the [documentation](https://captum.ai/api/neuron.html#neuron-conductance)).
In your case, this could simply be an integer specifying for which neuron in the linear output you want Captum to compute the gradients.

Hope this helps
