### ISSUE TITLE
pytest -ra fails

### ISSUE THREAD

**Issue by LutzWeischerFujitsu** [pytorch/captum#628]
[jw@cn06 captum]$ pytest -ra
================================================= test session starts ==================================================
platform linux -- Python 3.9.1, pytest-5.3.2, py-1.9.0, pluggy-0.13.1
rootdir: /data/jw/captum
plugins: cov-2.10.1, localserver-0.5.0, typeguard-2.10.0, anyio-2.1.0, requests-mock-1.7.0
collecting 0 items / 7 errors                                                                                          Fatal Python error: Segmentation fault

Current thread 0x0000ffff9b273da0 (most recent call first):
  File "/home/jw/.local/lib/python3.9/site-packages/_pytest/_code/source.py", line 324 in getstatementrange_ast
  File "/home/jw/.local/lib/python3.9/site-packages/_pytest/_code/code.py", line 241 in getsource
  File "/home/jw/.local/lib/python3.9/site-packages/_pytest/_code/code.py", line 679 in _getentrysource
  File "/home/jw/.local/lib/python3.9/site-packages/_pytest/_code/code.py", line 768 in repr_traceback_entry
  File "/home/jw/.local/lib/python3.9/site-packages/_pytest/_code/code.py", line 820 in repr_traceback
  File "/home/jw/.local/lib/python3.9/site-packages/_pytest/_code/code.py", line 876 in repr_excinfo
  File "/home/jw/.local/lib/python3.9/site-packages/_pytest/_code/code.py", line 630 in getrepr
  File "/home/jw/.local/lib/python3.9/site-packages/_pytest/nodes.py", line 319 in _repr_failure_py
  File "/home/jw/.local/lib/python3.9/site-packages/_pytest/nodes.py", line 378 in repr_failure
  File "/home/jw/.local/lib/python3.9/site-packages/_pytest/runner.py", line 270 in pytest_make_collect_report
  File "/home/jw/.local/lib/python3.9/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/home/jw/.local/lib/python3.9/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/home/jw/.local/lib/python3.9/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/home/jw/.local/lib/python3.9/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/home/jw/.local/lib/python3.9/site-packages/_pytest/runner.py", line 373 in collect_one_node
  File "/home/jw/.local/lib/python3.9/site-packages/_pytest/main.py", line 717 in genitems
  File "/home/jw/.local/lib/python3.9/site-packages/_pytest/main.py", line 720 in genitems
  File "/home/jw/.local/lib/python3.9/site-packages/_pytest/main.py", line 492 in _perform_collect
  File "/home/jw/.local/lib/python3.9/site-packages/_pytest/main.py", line 454 in perform_collect
  File "/home/jw/.local/lib/python3.9/site-packages/_pytest/main.py", line 255 in pytest_collection
  File "/home/jw/.local/lib/python3.9/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/home/jw/.local/lib/python3.9/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/home/jw/.local/lib/python3.9/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/home/jw/.local/lib/python3.9/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/home/jw/.local/lib/python3.9/site-packages/_pytest/main.py", line 245 in _main
  File "/home/jw/.local/lib/python3.9/site-packages/_pytest/main.py", line 196 in wrap_session
  File "/home/jw/.local/lib/python3.9/site-packages/_pytest/main.py", line 239 in pytest_cmdline_main
  File "/home/jw/.local/lib/python3.9/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/home/jw/.local/lib/python3.9/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/home/jw/.local/lib/python3.9/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/home/jw/.local/lib/python3.9/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/home/jw/.local/lib/python3.9/site-packages/_pytest/config/__init__.py", line 91 in main
  File "/home/jw/.local/bin/pytest", line 8 in <module>
Segmentation fault (core dumped)
[jw@cn06 captum]$

**Comment by NarineK** [comment]
@LutzWeischerFujitsu, which instructions did  you follow to install Captum ?
Have you tried to run single tests ? 
```
python -m unittest -v tests.attr.test_saliency
```
Is above unit test running ?

**Comment by LutzWeischerFujitsu** [comment]
[jw@cn06 captum]$ python -m unittest -v tests.attr.test_saliency
Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib64/python3.9/unittest/__main__.py", line 18, in <module>
    main(module=None)
  File "/usr/lib64/python3.9/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/usr/lib64/python3.9/unittest/main.py", line 147, in parseArgs
    self.createTests()
  File "/usr/lib64/python3.9/unittest/main.py", line 158, in createTests
    self.test = self.testLoader.loadTestsFromNames(self.testNames,
  File "/usr/lib64/python3.9/unittest/loader.py", line 220, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib64/python3.9/unittest/loader.py", line 220, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib64/python3.9/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/data/jw/captum/tests/attr/test_saliency.py", line 4, in <module>
    import torch
  File "/home/jw/.local/lib/python3.9/site-packages/torch/__init__.py", line 196, in <module>
    from torch._C import *
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
[jw@cn06 captum]$ python3 -m unittest -v tests.attr.test_saliency
test_saliency (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: test_saliency (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_saliency
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/data/jw/captum/tests/attr/test_saliency.py", line 4, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
[jw@cn06 captum]$ 

pip3 install works. Alternatively, git clone, pip3 install -e . Via setup.py a file is missing: error: can't copy 'captum/insights/attr_vis/widget/static/extension.js': doesn't exist or not a regular file

**Comment by edward-io** [comment]
I'm not sure why torch isn't importing for you, but the extension.js file is missing because Insights was not built. Try `BUILD_INSIGHTS=true python setup.py install`.

**Comment by LutzWeischerFujitsu** [comment]
Thanks. Now it proceeds. 
'pytest -ra' or the single test mentioned above do all fail, however 'pip3 install torch' (and 'pip3 install captum') works: 

(base) [jw@cn06 captum]$ python3 -m unittest -v tests.attr.test_saliency
test_saliency (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: test_saliency (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_saliency
Traceback (most recent call last):
  File "/home/jw/c4aarch64_installer/lib/python3.7/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/data/jw/captum/tests/attr/test_saliency.py", line 4, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
(base) [jw@cn06 captum]$

**Comment by NarineK** [comment]
@LutzWeischerFujitsu, is this still a problem for you ? I think that we weren't able to reproduce it.

**Comment by LutzWeischerFujitsu** [comment]
Solved using v0.4.0.
