### ISSUE TITLE
The lint_test_py37_conda test is currently failing due to an incorrect node engine version

### ISSUE THREAD

**Issue by ProGamerGov** [pytorch/captum#669]
## 🐛 Bug

The lint_test_py37_conda test is currently is failing with the following error:

```
-- Building version 0.3.0
-- Building Captum Insights
Running: ./scripts/build_insights.sh
~/project/captum/insights/attr_vis/frontend ~/project
-----------------------------------
Install Dependencies
-----------------------------------
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
error jest-diff@25.5.0: The engine "node" is incompatible with this module. Expected version ">= 8.3". Got "6.13.1"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Traceback (most recent call last):
  File "setup.py", line 104, in <module>
    build_insights()
  File "setup.py", line 87, in build_insights
    subprocess.check_call(command)
  File "/opt/conda/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command './scripts/build_insights.sh' returned non-zero exit status 1.

Exited with code exit status 1

CircleCI received exit code 1
```
 
https://app.circleci.com/pipelines/github/pytorch/captum/3105/workflows/bc433333-a1c6-41bb-ba8e-bb12a9465ae6/jobs/15714

**Comment by mullachv** [comment]
I just ran `./scripts/build_insights.sh` without any errors. Here is the output:
```
Using Yarn from ****/xplat/third-party/yarn/yarn
yarn install v1.17.0-20190429.1820
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.2: The platform "linux" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.12: The platform "linux" is incompatible with this module.
info "fsevents@1.2.12" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > @babel/plugin-proposal-class-properties@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/plugin-proposal-class-properties > @babel/helper-create-class-features-plugin@7.8.6" has unmet peer dependency "@babel/core@^7.0.0".
warning " > @babel/preset-typescript@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-typescript > @babel/plugin-transform-typescript@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-typescript > @babel/plugin-transform-typescript > @babel/helper-create-class-features-plugin@7.10.2" has unmet peer dependency "@babel/core@^7.0.0".
warning "@babel/preset-typescript > @babel/plugin-transform-typescript > @babel/plugin-syntax-typescript@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning " > babel-loader@8.1.0" has unmet peer dependency "@babel/core@^7.0.0".
warning " > babel-loader@8.1.0" has unmet peer dependency "webpack@>=2".
warning " > css-loader@3.3.0" has unmet peer dependency "webpack@^4.0.0".
warning " > react-tag-autocomplete@5.12.1" has unmet peer dependency "prop-types@^15.0.0".
warning " > webpack-cli@3.3.11" has unmet peer dependency "webpack@4.x.x".
[4/4] Building fresh packages...
Done in 33.08s.
-----------------------------------
Building Captum Insights
-----------------------------------
```

**Comment by ProGamerGov** [comment]
@mullachv I just ran the CircleCI instance test again, and it's using `yarn v1.22.10`:

https://app.circleci.com/pipelines/github/pytorch/captum/3108/workflows/3a38cdc8-bc01-4c7e-9c6d-091ce46aee21/jobs/15728

Maybe server or desktop that you ran the script on had some dependencies already installed or something like that?

**Comment by NarineK** [comment]
cc: @edward-io it looks like we had similar issues with the yarn. Can we, please, push a fix for this ?

**Comment by NarineK** [comment]
fixed - closing
