### ISSUE TITLE
Most CircleCI tests are currently failing due to a yarn related error

### ISSUE THREAD

**Issue by ProGamerGov** [pytorch/captum#789]
All branches seem to be experiencing this issue at the moment.

```
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
-- Building version 0.3.0
-- Building Captum Insights
Running: ./scripts/build_insights.sh
/home/circleci/project/captum/insights/attr_vis/frontend /home/circleci/project
-----------------------------------
Install Dependencies
-----------------------------------
/usr/share/yarn/lib/cli.js:46280
  let {
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/share/yarn/bin/yarn.js:24:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
Traceback (most recent call last):
  File "setup.py", line 104, in <module>
    build_insights()
  File "setup.py", line 87, in build_insights
    subprocess.check_call(command)
  File "/usr/local/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command './scripts/build_insights.sh' returned non-zero exit status 1.

Exited with code exit status 1

CircleCI received exit code 1
```

Error log pasted from: https://app.circleci.com/pipelines/github/pytorch/captum/3419/workflows/08d5a928-182e-4d52-9554-41fbed857b6e/jobs/17546

**Comment by NarineK** [comment]
@ProGamerGov , thank you for bringing up this issue. I think that it might have gotten fixed by now. I rerun the tests for your PR and see that there is currently only one flake / linter error.

https://app.circleci.com/pipelines/github/pytorch/captum?branch=pull%2F782
