### ISSUE TITLE
Attribute inputs for Pytorch Bi-Lstm 

### ISSUE THREAD

**Issue by SaidaSaad** [pytorch/captum#816]
Hi 

I have pytorch model composed of  Lstm layer followed by fc and another softmax layer.
I have some code same, takes sequence of length 341 and give one classes from {1,2,3} the model take batch of data  of shape [16,341] and return vector of length 16. I am new to Capium , I am trying to use Intergrated Garidient but the following code did not work, Also I tried to use Deeplift and Saliency but nothing works for me , Is there is something wrong in the code?

ig = IntegratedGradients(model)
test_input_tensor, targets = next(iter(testloader))
test_input_tensor =test_input_tensor.requires_grad_()
attr = ig.attribute(test_input_tensor, target = 0 , return_convergence_delta=False)
attr = attr.detach().numpy()

**Comment by bilalsal** [comment]
Hi @SaidaSaad ,

can you elaborate with code showing your how your model is defined, how the inputs look like, and what the error you are getting when calling `ig.attribute()`?

**Comment by SaidaSaad** [comment]
Hi @bilalsal 

Here is my modle 
'''
class PPS(nn.Module):
    def __init__(self):
        super(PPS, self).__init__()
        self.seq_len = 341
        self.n_hidden = 64
        self.numb_label = 3

        self.lstm1 = nn.LSTM(
            input_size=self.seq_len,
            hidden_size=self.n_hidden,
            num_layers=1,
            bidirectional=True,
            batch_first=True, dropout=0.2)

        self.fc1 = nn.Linear(64 * 2, 32)
        self.fc2 = nn.Linear(32, 3)
        self.sof = nn.LogSoftmax(dim=-1)

        self.tanhlay = nn.Sequential(nn.Tanh())
        self.relu = nn.Sequential(nn.ReLU())
        self.leakyrelu = nn.Sequential(nn.LeakyReLU(0.01))

    def forward(self, x):
        x = x.squeeze(-1).unsqueeze(1)
        out, (_, _) = self.lstm1(x)
        out = self.fc1(out)
        out = self.relu(out)
        out = self.fc2(out)
        out = self.sof(out)
        return out
'''
My training is 

for epoch in range(0, N_EPOCHES):
    model.train()
    print(f'Starting epoch {epoch + 1}')
    for i, data in enumerate(trainloader, 0):
        inputs, targets = data
        inputs = inputs.unsqueeze(-1)
        optimizer.zero_grad()
        outputs = model(inputs)
        outputs = outputs.squeeze()
         loss = loss_function(outputs, targets)
        loss.backward()
        optimizer.step()
        running_loss += loss.item()
        acclist.append((outputs.argmax(1) == targets).float().mean())

I got that error

""
Traceback (most recent call last):
  File "/mnt/HDD/VE/Seq_align/Re__Re_/Repeat_Experiment3/Experiment_senza_CRF/train_model.py", line 247, in <module>
    attr = ig.attribute(test_input_tensor, target= 0, return_convergence_delta=False)
  File "/home/Guest/.local/lib/python3.6/site-packages/captum/log/__init__.py", line 35, in wrapper
    return func(*args, **kwargs)
  File "/home/Guest/.local/lib/python3.6/site-packages/captum/attr/_core/integrated_gradients.py", line 291, in attribute
    method=method,
  File "/home/saida/.local/lib/python3.6/site-packages/captum/attr/_core/integrated_gradients.py", line 354, in _attribute
    additional_forward_args=input_additional_args,
  File "/home/Guest/.local/lib/python3.6/site-packages/captum/_utils/gradient.py", line 113, in compute_gradients
    "Target not provided when necessary, cannot"
AssertionError: Target not provided when necessary, cannot take gradient with respect to multiple outputs.

"""

**Comment by bilalsal** [comment]
Hi @SaidaSaad ,

can you please print the shape of `outputs = model(inputs)`?

**Comment by SaidaSaad** [comment]
Hi @bilalsal  thank you so much for your reply , I discovered the problem in the shape of the output of the forward function and it  solved, it was (16,1,3) and i squeeze it to (16,3). And i was able to have the attributes . But Now I have to initialize the hidden state of Lstm by zeros because it effect the performance of the model and when i did that i got an error related to the hidden shape, below the forward function and the error 
'''
    def forward(self, x):
        h0 = torch.zeros(self.n_layers, BATCH_SIEZ, self.n_hidden)
        h0.requires_grad = True

        c0 = torch.zeros(self.n_layers, BATCH_SIEZ, self.n_hidden)
        c0.requires_grad = True
        h0, c0 = h0.cuda(), c0.cuda()

        x = x.squeeze(-1).unsqueeze(1)
        out, (_, _) = self.lstm1(x,(h0, c0))

        out = self.fc1(out)
        out = self.relu(out)
        out = self.fc2(out)
        out = self.sof(out)
        out = out.squeeze()
        return out
'''
I got that error 
""
Traceback (most recent call last):
  File "/mnt/HDD//Captum_analysis.py", line 153, in <module>
    attr = ig.attribute(test_input_tensor, target=targets.to("cuda:0"), return_convergence_delta=False)
  File "/home/saida/.local/lib/python3.6/site-packages/captum/log/__init__.py", line 35, in wrapper
    return func(*args, **kwargs)
  File "/home/saida/.local/lib/python3.6/site-packages/captum/attr/_core/integrated_gradients.py", line 291, in attribute
    method=method,
  File "/home/saida/.local/lib/python3.6/site-packages/captum/attr/_core/integrated_gradients.py", line 354, in _attribute
    additional_forward_args=input_additional_args,
  File "/home/saida/.local/lib/python3.6/site-packages/captum/_utils/gradient.py", line 111, in compute_gradients
    outputs = _run_forward(forward_fn, inputs, target_ind, additional_forward_args)
  File "/home/saida/.local/lib/python3.6/site-packages/captum/_utils/common.py", line 459, in _run_forward
    else inputs
  File "/home/saida/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/HDD/VE_Saida/Captum_analysis.py", line 110, in forward
    out, (_, _) = self.lstm1(x,(h0, c0))
  File "/home/saida/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/saida/.local/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 689, in forward
    self.check_forward_args(input, hx, batch_sizes)
  File "/home/saida/.local/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 634, in check_forward_args
    'Expected hidden[0] size {}, got {}')
  File "/home/saida/.local/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 226, in check_hidden_size
    raise RuntimeError(msg.format(expected_hidden_size, list(hx.size())))
RuntimeError: Expected hidden[0] size (2, 800, 64), got [2, 16, 64]
Process finished with exit code 1
""

**Comment by bilalsal** [comment]
Hi @SaidaSaad ,

does your forward function work if you call it directly? 
Form the stack trace, the error does not seem to stem from Captum, AFAIK.
To help isolate the issue, I recommend you call your forward function directly.
In addition, you could try Captum's Occlusion or FeatureAblation algorithm, to find out if `IntegratedGradient` is causing the issue.

Hope this helps

**Comment by SaidaSaad** [comment]
@bilalsal  model works directly , i tried to change the output to be one hot vector for each class [1,0,0], [0,1,0],[0,0,1]
and my forward function return batch size= 16 * 3, so i tried this 
attr_test = ig.attribute(test_input_tensor, target=targets_1.to("cuda:0"))
where test_input_tensor is 16*341 and targets_1 is 16*3 and it gave me that error
Traceback (most recent call last):
  File "/mnt/HDD/VE_Saida/Seq_align/Re__Re_/Repeat_Experiment3/Experimet+12Nov/Captum_analysis.py", line 163, in <module>
    attr_test = ig.attribute(test_input_tensor, target=targets_1.to("cuda:0"))
  File "/home/saida/.local/lib/python3.6/site-packages/captum/log/__init__.py", line 35, in wrapper
    return func(*args, **kwargs)
  File "/home/saida/.local/lib/python3.6/site-packages/captum/attr/_core/feature_ablation.py", line 278, in attribute
    self.forward_func, inputs, target, additional_forward_args
  File "/home/saida/.local/lib/python3.6/site-packages/captum/_utils/common.py", line 461, in _run_forward
    return _select_targets(output, target)
  File "/home/saida/.local/lib/python3.6/site-packages/captum/_utils/common.py", line 482, in _select_targets
    % (target.shape, output.shape)
AssertionError: Tensor target dimension torch.Size([16, 3]) is not valid. torch.Size([16, 3])

**Comment by bilalsal** [comment]
Hi @SaidaSaad,

assuming your model's output is a 1-D tensor [p_1, p_2, p_3] (with p_i being the probability of each of the three classes you mentioned), the `target` parameter in `ig.attribute` must either be an `int` (representing one of the 3 classes) or 1-D tensor of ints (so that each sample in the batch can have a different attribution target).

Hope this helps. 
Have a good start of the new year!

**Comment by SaidaSaad** [comment]
Hi @bilalsal  , Thank you so much , I hope you have Good start .
I gave my model batch of 1D tensor of length 341 , and target are one of those classes  [0,0,1].[0,1,0] and [1,0,0].
Yes you are right, my output vector from the model is 1-D tensor [p_1, p_2, p_3].
 I did not get when u day I gave ig.attribute targets as integers? because my classes are not integers .

**Comment by bilalsal** [comment]
Hi @SaidaSaad ,

the integers represent your 3 classes, because Captum expects a class to be the index of as an output neuron.
Could you try feeding one of 0, 1, or 2 as the `target` parameter? This target will then be used for ALL your samples.

You can also feed a 1D vector (e.g. [0, 0, 1, 0, 2, 1, 0] if you feed 7 samples in one batch and want to use a different attribution targets.

Hope this helps.

**Comment by SaidaSaad** [comment]
Hi @bilalsal.  Yes it helps and it works fine.
I appreciate a lot your help and Thank you so much for your replies.
