### ISSUE TITLE
Error while running segmentation tutorial

### ISSUE THREAD

**Issue by akashlp27** [pytorch/captum#944]
While running the segmentation tutorial I am getting this error 
attached is the full traceback:
`Traceback (most recent call last):
  File "C:/Users/user/PycharmProjects/Captum_test/segmentation_example.py", line 99, in <module>
    viz.visualize_image_attr(gc_attr[0].cpu().permute(1, 2, 0).detach().numpy(), sign="all")
  File "C:\Users\user\PycharmProjects\pythonProject\venv\lib\site-packages\captum\attr\_utils\visualization.py", line 244, in visualize_image_attr
    norm_attr = _normalize_image_attr(attr, sign, outlier_perc)
  File "C:\Users\user\PycharmProjects\pythonProject\venv\lib\site-packages\captum\attr\_utils\visualization.py", line 84, in _normalize_image_attr
    return _normalize_scale(attr_combined, threshold)
  File "C:\Users\user\PycharmProjects\pythonProject\venv\lib\site-packages\captum\attr\_utils\visualization.py", line 42, in _normalize_scale
    assert scale_factor != 0, "Cannot normalize by scale factor = 0"
AssertionError: Cannot normalize by scale factor = 0`

I am using **models.segmentation.fcn_resnet50** instead of **models.segmentation.fcn_resnet101**

**Comment by NarineK** [comment]
@akashlp27, do you mind attaching your colab notebook here so that we can debug it ?

**Comment by craymichael** [comment]
Closing due to inactivity.
